revature-quizzard/quizzard-ui

src/components/Flashcards/FlipCard.tsx, src/components/StudySets/StudyListTable.tsx, src/index.css
Please approve and merge before we move on to next bug
=> fixed one bug, pushing and merging, then moving on to next bug

src/__tests__/flip-card.test.tsx, src/__tests__/login.test.ts, src/__tests__/login.test.tsx, src/__tests__/quiz-utility.test.tsx, src/__tests__/subject-service.test.tsx, src/components/Login/Login.tsx, src/components/Register/Register.tsx, src/components/Sets/Sets.tsx, src/components/StudySets/StudyListTable.tsx
There was a merge conflict that failed but was pushed. It is now reverted and fixed
=> Revert to working

src/components/CreateQuiz/Results.tsx, src/remote/api-url.ts
Ready for pre_dev and CICD deployment
=> cleaned up quiz results.

package.json, src/App.tsx, src/components/Login/ConfirmSignup.tsx, src/components/Login/ErrorMessageComponent.tsx, src/components/Login/Login.tsx, src/components/NavBar/Navigation.tsx, src/components/Register/Register.tsx, src/components/StudySets/StudyHub.tsx, src/config/aws.ts, src/dtos/credentials.ts, src/dtos/principal.ts, src/dtos/register-user-request.ts, src/models/user.ts, src/remote/api-url.ts, src/remote/login-register-service.ts, src/state-slices/auth/auth-slice.tsx
There are quite a few changes to the way login functionality is done, and other validation has even been placed in other classes, conditional rendering for if the user is logged in and authenticated or not. I feel refraining from pulling these things to Main would result in disastrous merge conflicts later on, once the ball has been rolling.
=> Login functionality is looking nice.

src/components/Multiplayer/GameSettings.tsx
Laid out breadcrumbs for game settings
=> Game Settings Breadcrumbs

src/components/Multiplayer/Answers.tsx
Signed-off-by: hguilfoyle <hguilfoyle1@gmail.com>
=> answer breadcrumbs its a start decisions still need to be made

src/App.tsx, src/__tests__/multiplayer-tests/game-settings.test.tsx, src/__tests__/multiplayer-tests/game.test.tsx, src/components/Multiplayer/CreateGame.tsx, src/components/Multiplayer/Game.tsx, src/components/Multiplayer/GameLounge.tsx
Split Game into two containers: lounge and game
Added more breadcrumbs
=> G/graph ql breadcrumbs/sean

src/components/Login/Login.tsx, src/state-slices/error/errorSlice.ts
Fixed error when logging in with bad credentials and added setErrorSeverity reducer to errorSlice.ts for changing error severity. Also fixed duplicate error message.
=> Fix login bugs

package.json, src/App.tsx, src/components/Login/Login.tsx, src/components/NavBar/Navigation.tsx, src/components/StudySets/AddFlashcardModal.tsx, src/components/StudySets/StudyListTable.tsx, src/components/StudySets/_OwnedStudySetData.tsx, src/components/StudySets/_PublicStudySetData.tsx, src/components/UserProfile/UserProfile.tsx, src/components/UserProfile/UserProfileContainer.tsx, src/models/set-document.ts, src/models/tag.ts, src/models/user-data.ts, src/models/user.ts, src/remote/api-url.ts, src/remote/login-register-service.ts, src/remote/user-service.ts, src/state-slices/auth/auth-slice.tsx, src/state-slices/user-profile/profile-slice.ts, src/store/store.ts
Can now retrieve user information and display it in their profile. Barebones styling for now.
Note that the auth-slice token has been moved into the authUser object.
=> User profile

src/components/Multiplayer/Game.tsx, src/components/Multiplayer/GameLounge.tsx, src/components/Multiplayer/Questions.tsx
- Dummy Create Game button on /lounge
- Users can join game without being logged in (this implementation will likely change later)
- Connected components in /multiplayer to render properly
=> G/component connection/sean

src/components/Multiplayer/Answers.tsx, src/components/Multiplayer/Game.tsx, src/components/Multiplayer/GameLounge.tsx, src/utilities/game-utility.ts, src/utilities/quiz-utility.ts
This just reorganizes some of the answer logic that we have,
Created a game-utility (not completed) for logic that needs to be done.
Removed Answer logic from the Game component and placed it into the Answer Component
=> G/answer utility/heather

src/components/UserProfile/UserFavoriteSets.tsx, src/components/UserProfile/UserGameRecords.tsx, src/components/UserProfile/UserProfile.tsx, src/components/UserProfile/UserProfileContainer.tsx, src/components/UserProfile/UserSets.tsx
=> Added documentation

src/components/Multiplayer/GameLounge.tsx
Snackbars now appear for when you try to join a game you should not.
=> G/game errors/heather

src/components/Multiplayer/Game.tsx, src/components/Multiplayer/Leaderboard.tsx, src/components/Multiplayer/Players.tsx, src/index.css
The players list now reads from the Game state slice. As opposed to reading from a fake list called 'rows'.
Furthermore, the spacing has been decreased, allowing more screen area to the game object.
=> Made stylistic changes.

src/state-slices/multiplayer/guest-slice.ts, src/store/store.ts
=> G/group redux slice/heather

src/components/Multiplayer/GameLounge.tsx, src/components/Multiplayer/GameSettings.tsx
- Users can now join games as a guest, as long as they set a nickname
- Users can *theoretically* create games as a guest, though presently they cannot choose from any sets
- Error checking cleaned up a bit
=> G/guest login/sean

src/components/Multiplayer/Game.tsx, src/components/Multiplayer/Players.tsx, src/state-slices/multiplayer/game-slice.ts
The feature hath been implemented. Maybe something that automatically detects when the player is no longer viewing the page would be nice, since it would remove them automatically? (executeKick) them from the game?
=> G/kick players/john

src/components/Multiplayer/Game.tsx
* startGame method checks to see the matchState is 0 and updates it to 1. This starts the game for the players.
* closeGame method checks to see matchState is 3 and will delete the game from the database.
=> Worked on starting and closing a game

src/components/Multiplayer/Game.tsx, src/components/Multiplayer/GameLounge.tsx, src/components/Multiplayer/GameSettings.tsx, src/components/Multiplayer/Players.tsx, src/state-slices/multiplayer/guest-slice.ts
- Guest functionality is implemented for joining and playing a game
- Host checks *should* function correctly now
=> G/guest game/sean

src/components/Multiplayer/Answers.tsx, src/utilities/game-utility.ts
- Answers are dynamically assigned class names for selectedAnswer, correctAnswer, and wrongAnswer
- Fixed correct answers not submitting correctly
=> G/answers expansion/sean

src/components/Forum/AddComment.tsx, src/components/Forum/AddThread.tsx, src/components/Forum/GetThread.tsx, src/components/Forum/UpdateComment.tsx, src/components/Forum/UpdateThread.tsx, src/components/Forum/ViewComments.tsx
UI components being put together
=> Bringing it together/luna

src/components/Forum/AddComment.tsx, src/components/Forum/GetThread.tsx, src/components/Forum/Subforum.tsx, src/components/Forum/ViewComments.tsx
styled forum. Added darker backgrounds, changed font colors, and updated the look of the site overall.
=> Forum styling/luna

src/components/Multiplayer/Answers.tsx
During a game, when the timer runs out, the user will see the correct and incorrect answers. When the next question is displayed, the answers will change and all previously selected options will no longer be selected.
=> fixed randomizing answers and colors

src/components/Multiplayer/GameSettings.tsx, src/components/Multiplayer/Players.tsx
=> G/qol changes/john

src/components/Multiplayer/Game.tsx, src/components/Multiplayer/Players.tsx
When playing a game, the scoreboard will be sorted from highest to lowest points
=> Sorts the player list in game

src/components/NavBar/Navigation.tsx, src/components/UserProfile/UserProfileContainer.tsx, src/state-slices/user-profile/profile-slice.ts
Whoever did the navbar didn't carry over much functionality.
=> fixed logout and refactored navbar to render list items conditionally

src/components/Multiplayer/Game.tsx, src/components/NavBar/Navigation.tsx
- Fixed scores being sent twice
- Reset placing on players before persisting game records, according to total score
=> G/scoring tweaks/sean

src/__tests__/multiplayer-tests/game-settings.test.tsx, src/__tests__/multiplayer-tests/game.test.tsx, src/components/Multiplayer/Players.tsx
Did it in fifteen. This should appease our target audience; now the button displays outside of the player list component
(no idea why they think it is the leaderboard. the leaderboard is completely different!)
=> G/leave button/john

src/components/NavBar/Navigation.tsx, src/remote/login-register-service.ts
Fixed issue when a user logs in for the first time, the request headers do not include the "Authorization" header. Also modified logout button to call logout functionality to clear credentials from storage.
=> fixed the request headers and logout functionality
